version: '3.4'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:     
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './shared/nginx/vhost.d:/etc/nginx/vhost.d'
      - './shared/nginx/certs:/etc/nginx/certs:ro'
    networks:
      proxy: null
      commonnet:
        aliases:
          - api.etsprop.ru         
    restart: always
  common.api:
    image: 'etstrading/commonapi'
    build:
      context: .
      dockerfile: BinanceSimbols/Dockerfile
    container_name: commonapi
    environment:
      - VIRTUAL_HOST=api.etsprop.ru     
      - ASPNETCORE_ENVIRONMENT=Development       
    volumes:    
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      commonnet: null      
networks:
  proxy:
    driver: bridge
  commonnet:
    driver: bridge
